<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SKAnimation</AssemblyName>
    <RootNamespace></RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CS1591;CS0618;CS8981;CS0108;CS0114;CS0109;CS0169;CS0414;CS0649;CS0067;CS0168;CS0219</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../FarseerPhysicsXNA/FarseerPhysicsXNA.csproj" />
  </ItemGroup>
</Project>
